<div class="container">

    <ul class="tabs-list">
        <li data-class="tap-1" class="active-tab"> المستخدمين</li>
        <li data-class="tap-2"> الهواتف</li>
        <li data-class="tap-3"> المقالات</li>
    </ul>


    <div class="taps-content">


        <!-- Start -->
        <!-- ============== Tap 1 ============== -->
        <div class="tap-1 hide-div">

            <span>1</span>

        </div>
        <!-- ============== Tap 1 ============== -->
        <!-- End -->




        <!-- Start -->
        <!-- ============== Tap 2 ============== -->
        <div class="tap-2 hide-div">

            <span>2</span>


        </div>
        <!-- ============== Tap 2 ============== -->
        <!-- End -->




        <!-- Start -->
        <!-- ============== Tap 3 ============== -->
        <div class="tap-3 hide-div">

            <span>3</span>

        </div>
        <!-- ============== Tap 3 ============== -->
        <!-- End -->


        
    </div>

</div>

