

            </section>
            <!-- End Content -->

            <!-- Start Sidebar -->
            <aside class="sidebar">
            
                <!-- Start Ads Box 250x250 -->
                <div class="ads-box ads_250-250">
                    <img src="https://via.placeholder.com/250x250.png" alt="">
                </div>
                <!-- End Ads Box 250x250 -->


                <!-- Start Login Box -->
<!-- 
                <div class="login-box">
   
                <h3>تسجيل الدخول</h3>

                <div class="form-taps-content">
                    
                    <div class="tap-1 tap-style">

                    <form action="includes/function/login.php" method="POST" >
                        <input  type="email"     name="login_email"     placeholder="البريد الألكتروني" required>
                        <input  type="password"  name="login_password"     placeholder="كلمة السر" minlength="8" maxlength="16" required>
                        <button type="submit">تسجيل دخول</button>
                    </form>

                    </div>

                </div>
            </div> -->

                <!-- End Login Box -->


                <!-- Start Ads Box 250x500 -->
                <div class="ads-box ads_250-500">
                    <img src="02.png" alt="">
                </div>
                <!-- End Ads Box 250x500 -->

            </aside>
            <!-- End Sidebar -->
            
        </div>
    </div>
    <!-- End Main Body -->

    <!-- Start Footer -->
    <div class="container">
        <div class="first-footer">
                <div class="footer-box-holder">

                    <div class="about-box">
                        <h2>من نحن</h2>
                        <ul>
                            <li>
                                <p>موقع متخصص في تقديم المحتوي التقني الخاص بالهواتف.</p>
                            </li>
                            <li>
                                <h3>نهدف الي</h3>
                                <p>نشر المعرفة التي تمكن المستخدمين من الاستفادة الجيدة من الهواتف والتعرف علي مميزاتها.<br>
                                ومساعدة المستخدمين من اختيار الهاتف المناسب لهم.
                                </p>

                                <p></p>
                            </li>
                
                        </ul>
                    </div>

                    <div class="links-box">

                        <h2>تصفح الموقع</h2>

                        <ul class="links-box-ul">
                            <li><a href="#">اخر المقالات</a></li>
                            <li><a href="#">مقارانات الهواتف</a></li>
                            <li><a href="#">الأشتراك</a></li>
                            <li><a href="#">الأسئلة الشائعة</a></li>
                            <li><a href="#">أحدث الهواتف</a></li>

                        </ul>
                
                    </div>
                    
                    <div class="icons-box">
                        <h2>تابعنا</h2>
                        <p>
                            قم بمتابعتنا ليصلك كل جديد,<br>
                            ولمعرفة اخر الاخبار التقنية.<br>
                            <strong>1030450776&#40;20&#43;&#41;</strong>
                        </p>
                
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                            <li><a href="#"><i class="fa-brands fa-tiktok"></i></a></li>
                        </ul>
                    </div>

                </div>
            
            </div>
        <footer class="footer">
            <p> جميع الحقوق محفوظة الي موبزون &copy;</p>
        </footer>
    </div>


    <!-- End Footer -->

    <!-- Start Go To Top Button -->
    <button class="gotop"><i class="fa-solid fa-angle-up"></i></button>


    <!-- End Go To Top Button -->
 
    <!-- JS Files -->
    <script src="<?php echo $js; ?>jquery-3.6.0.min.js"></script>
    <script src="https://kit.fontawesome.com/07bb446ef7.js" crossorigin="anonymous"></script>
    <script src="<?php echo $js; ?>main.js"></script>

      

</body>
</html>