<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="copyright" content="موبزون" />

    <title><?php getTitle() ?></title>


    <!-- Css Files -->
    <link rel="preconnect" href="https://fonts.googleapis.com"> <!-- Font Family -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <!-- Font Family -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;700&display=swap"> <!-- Font Family -->


    <link rel="stylesheet" href="<?php echo $css; ?>normalize.css"><!-- Normalize File -->
    <link rel="stylesheet" href="<?php echo $css; ?>main.css"> <!-- Main CSS File -->





    
</head>

